CREATE VIEW VIEW_USER_INFORMATIO AS
SELECT CAST(U.USER_ID AS VARCHAR2(100)), U.FIRST_NAME, U.LAST_NAME, CAST(U.YEAR_OF_BIRTH AS NUMBER(38)), CAST(U.MONTH_OF_BIRTH AS NUMBER(38)), CAST(U.DAY_OF_BIRTH AS NUMBER(38)), U.GENDER, CC.CITY_NAME, CC.STATE_NAME, CC.COUNTRY_NAME, HC.CITY_NAME, HC.STATE_NAME, HC.COUNTRY_NAME, P.INSTITUTION, CAST(E.PROGRAM_YEAR AS NUMBER(38)), CAST(P.CONCENTRATION AS CHAR(100)), P.DEGREE
FROM USERS U 
LEFT JOIN USER_CURRENT_CITY UCC ON U.USER_ID = UCC.USER_ID
LEFT JOIN CITIES CC ON UCC.CURRENT_CITY_ID = CC.CITY_ID
LEFT JOIN USER_HOMETOWN_CITY UHC ON U.USER_ID = UHC.USER_ID
LEFT JOIN CITIES HC ON UHC.HOMETOWN_CITY_ID = HC.CITY_ID
LEFT JOIN EDUCATION E ON U.USER_ID = E.USER_ID
LEFT JOIN PROGRAMS P ON E.PROGRAM_ID = P.PROGRAM_ID;

CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT CAST(USER1_ID AS VARCHAR2(100)), CAST(USER2_ID AS VARCHAR2(100))
FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT A.ALBUM_ID, CAST(A.ALBUM_OWNER_ID AS VARCHAR2(100)), A.COVER_PHOTO_ID, A.ALBUM_NAME, A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK, A.ALBUM_VISIBILITY, P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK 
FROM ALBUMS A
LEFT JOIN PHOTOS P ON A.ALBUM_ID = P.ALBUM_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT TAG_PHOTO_ID, CAST(TAG_SUBJECT_ID AS VARCHAR2(100)), TAG_CREATED_TIME, TAG_X, TAG_Y
FROM TAGS;

CREATE VIEW VIEW_EVENT_INFORMATION AS
SELECT CAST(E.EVENT_ID AS VARCHAR2(100)), CAST(E.EVENT_CREATOR_ID AS VARCHAR2(100)), E.EVENT_NAME, E.EVENT_TAGLINE, E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE, E.EVENT_LOCATION, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, E.EVENT_START_TIME, E.EVENT_END_TIME
FROM USER_EVENTS E 
LEFT JOIN CITIES C ON E.EVENT_CITY_ID = C.CITY_ID;