ALTER TABLE TAGS
    DROP CONSTRAINT user_id_in_tag;
DROP TABLE TAGS;
-- ALTER TABLE PHOTOS
--     DROP CONSTRAINT album_id_in_photos;
ALTER TABLE ALBUMS 
    DROP CONSTRAINT photo_id_in_albums;
ALTER TABLE ALBUMS
    DROP CONSTRAINT user_id_in_albums;
DROP TABLE PHOTOS;
DROP TABLE ALBUMS;
ALTER TABLE PARTICIPANTS
    DROP CONSTRAINT foreign_id_in_participants;
DROP TABLE PARTICIPANTS;
ALTER TABLE USER_EVENTS
    DROP CONSTRAINT foreign_id_in_user_events;
DROP TABLE USER_EVENTS;
ALTER TABLE EDUCATION
    DROP CONSTRAINT foreign_id_in_education;
DROP TABLE EDUCATION;
DROP TRIGGER program_id_trigger;
DROP SEQUENCE program_id_counter;
DROP TABLE PROGRAMS;
ALTER TABLE MESSAGES
    DROP CONSTRAINT user_id_in_messages;
DROP TABLE MESSAGES;
-- ALTER TABLE USER_HOMETOWN_CITIES
--     DROP CONSTRAINT city_id_in_hometown_cities;
DROP TABLE USER_HOMETOWN_CITIES;
-- ALTER TABLE USER_CURRENT_CITIES
--     DROP CONSTRAINT city_id_in_current_cities;
DROP TABLE USER_CURRENT_CITIES;
DROP TRIGGER city_id_trigger;
DROP SEQUENCE city_id_counter;
DROP TABLE CITIES;
DROP TRIGGER order_friends_pairs;
ALTER TABLE FRIENDS
    DROP CONSTRAINT user_id_in_friends;
DROP TABLE FRIENDS;
DROP TABLE USERS;


