INSERT INTO USERS
SELECT DISTINCT USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER
FROM jsoren.PUBLIC_USER_INFORMATION;

INSERT INTO FRIENDS 
SELECT DISTINCT 
    CASE WHEN USER1_ID > USER2_ID THEN USER1_ID ELSE USER2_ID END as USER1_ID,
    CASE WHEN USER1_ID > USER2_ID THEN USER2_ID ELSE USER1_ID END as USER2_ID
FROM jsoren.PUBLIC_ARE_FRIENDS;

INSERT INTO CITIES(CITY_NAME, STATE_NAME, COUNTRY_NAME)
SELECT DISTINCT CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY
FROM jsoren.PUBLIC_USER_INFORMATION;

INSERT INTO CITIES(CITY_NAME, STATE_NAME, COUNTRY_NAME)
SELECT DISTINCT P.HOMETOWN_CITY, P.HOMETOWN_STATE, P.HOMETOWN_COUNTRY
FROM jsoren.PUBLIC_USER_INFORMATION P, CITIES C
WHERE P.HOMETOWN_CITY != C.CITY_NAME AND P.HOMETOWN_STATE != C.STATE_NAME AND P.HOMETOWN_COUNTRY != C.COUNTRY_NAME;

INSERT INTO USER_CURRENT_CITIES
SELECT DISTINCT P.USER_ID, C.CITY_ID
FROM jsoren.PUBLIC_USER_INFORMATION P, CITIES C
WHERE P.CURRENT_CITY = C.CITY_NAME AND P.CURRENT_STATE = C.STATE_NAME AND P.CURRENT_COUNTRY = C.COUNTRY_NAME;

INSERT INTO USER_HOMETOWN_CITIES
SELECT DISTINCT P.USER_ID, C.CITY_ID
FROM jsoren.PUBLIC_USER_INFORMATION P, CITIES C
WHERE P.HOMETOWN_CITY = C.CITY_NAME AND P.HOMETOWN_STATE = C.STATE_NAME AND P.HOMETOWN_COUNTRY = C.COUNTRY_NAME;

INSERT INTO PROGRAMS(INSTITUTION, CONCENTRATION, DEGREE)
SELECT DISTINCT INSTITUTION_NAME, PROGRAM_CONCENTRATION, PROGRAM_DEGREE
FROM jsoren.PUBLIC_USER_INFORMATION
WHERE INSTITUTION_NAME IS NOT NULL AND PROGRAM_CONCENTRATION IS NOT NULL AND PROGRAM_DEGREE IS NOT NULL; 

INSERT INTO EDUCATION
SELECT U.USER_ID, P.PROGRAM_ID, I.PROGRAM_YEAR 
FROM USERS U, jsoren.PUBLIC_USER_INFORMATION I, PROGRAMS P
WHERE I.USER_ID = U.USER_ID AND I.INSTITUTION_NAME = P.INSTITUTION AND I.PROGRAM_CONCENTRATION = P.CONCENTRATION AND I.PROGRAM_DEGREE = P.DEGREE;

INSERT INTO USER_EVENTS(EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_ADDRESS, EVENT_CITY_ID, EVENT_START_TIME, EVENT_END_TIME)
SELECT DISTINCT P.EVENT_ID, P.EVENT_CREATOR_ID, P.EVENT_NAME, P.EVENT_TAGLINE, P.EVENT_DESCRIPTION, P.EVENT_HOST, P.EVENT_TYPE, P.EVENT_SUBTYPE, P.EVENT_ADDRESS, C.CITY_ID, P.EVENT_START_TIME, P.EVENT_END_TIME
FROM jsoren.PUBLIC_EVENT_INFORMATION P, CITIES C
WHERE C.CITY_NAME = P.EVENT_CITY AND C.STATE_NAME = P.EVENT_STATE AND C.COUNTRY_NAME = P.EVENT_COUNTRY;

INSERT INTO ALBUMS
SELECT DISTINCT ALBUM_ID, OWNER_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, COVER_PHOTO_ID
FROM jsoren.PUBLIC_PHOTO_INFORMATION;

INSERT INTO PHOTOS
SELECT DISTINCT PHOTO_ID, ALBUM_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK
FROM jsoren.PUBLIC_PHOTO_INFORMATION;

INSERT INTO TAGS
SELECT DISTINCT PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE
FROM jsoren.PUBLIC_TAG_INFORMATION;


 

